/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module ripple_carry_adder_synthesized(a, b, clk, cin, sum, cout, overflow);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  input [31:0] a;
  wire [31:0] a;
  input [31:0] b;
  wire [31:0] b;
  wire \bit_adder[0].FA.sum ;
  wire \bit_adder[10].FA.sum ;
  wire \bit_adder[11].FA.sum ;
  wire \bit_adder[12].FA.sum ;
  wire \bit_adder[13].FA.sum ;
  wire \bit_adder[14].FA.sum ;
  wire \bit_adder[15].FA.sum ;
  wire \bit_adder[16].FA.sum ;
  wire \bit_adder[17].FA.sum ;
  wire \bit_adder[18].FA.sum ;
  wire \bit_adder[19].FA.sum ;
  wire \bit_adder[1].FA.sum ;
  wire \bit_adder[20].FA.sum ;
  wire \bit_adder[21].FA.sum ;
  wire \bit_adder[22].FA.sum ;
  wire \bit_adder[23].FA.sum ;
  wire \bit_adder[24].FA.sum ;
  wire \bit_adder[25].FA.sum ;
  wire \bit_adder[26].FA.sum ;
  wire \bit_adder[27].FA.sum ;
  wire \bit_adder[28].FA.sum ;
  wire \bit_adder[29].FA.sum ;
  wire \bit_adder[2].FA.sum ;
  wire \bit_adder[30].FA.sum ;
  wire \bit_adder[31].FA.sum ;
  wire \bit_adder[3].FA.sum ;
  wire \bit_adder[4].FA.sum ;
  wire \bit_adder[5].FA.sum ;
  wire \bit_adder[6].FA.sum ;
  wire \bit_adder[7].FA.sum ;
  wire \bit_adder[8].FA.sum ;
  wire \bit_adder[9].FA.sum ;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output cout;
  wire cout;
  output overflow;
  wire overflow;
  output [31:0] sum;
  wire [31:0] sum;
  sky130_fd_sc_hd__inv_2 _216_ (
    .A(b[30]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__inv_2 _217_ (
    .A(a[30]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__inv_2 _218_ (
    .A(b[28]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__inv_2 _219_ (
    .A(a[28]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_2 _220_ (
    .A(b[26]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__inv_2 _221_ (
    .A(a[26]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_2 _222_ (
    .A(b[23]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__inv_2 _223_ (
    .A(a[23]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__inv_2 _224_ (
    .A(b[21]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__inv_2 _225_ (
    .A(a[21]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__inv_2 _226_ (
    .A(b[20]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__inv_2 _227_ (
    .A(a[20]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__inv_2 _228_ (
    .A(b[18]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__inv_2 _229_ (
    .A(a[18]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_2 _230_ (
    .A(b[16]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__inv_2 _231_ (
    .A(a[16]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_2 _232_ (
    .A(b[15]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_2 _233_ (
    .A(a[15]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__inv_2 _234_ (
    .A(b[13]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__inv_2 _235_ (
    .A(a[13]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__inv_2 _236_ (
    .A(b[11]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__inv_2 _237_ (
    .A(a[11]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__inv_2 _238_ (
    .A(b[10]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__inv_2 _239_ (
    .A(a[10]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__inv_2 _240_ (
    .A(b[8]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__inv_2 _241_ (
    .A(a[8]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__inv_2 _242_ (
    .A(b[6]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__inv_2 _243_ (
    .A(a[6]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_2 _244_ (
    .A(b[4]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_2 _245_ (
    .A(a[4]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_2 _246_ (
    .A(b[2]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__inv_2 _247_ (
    .A(a[2]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2_2 _248_ (
    .A(b[31]),
    .B(a[31]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__or2_2 _249_ (
    .A(b[31]),
    .B(a[31]),
    .X(_033_)
  );
  sky130_fd_sc_hd__and2_2 _250_ (
    .A(b[31]),
    .B(a[31]),
    .X(_034_)
  );
  sky130_fd_sc_hd__nand2_2 _251_ (
    .A(b[31]),
    .B(a[31]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__or2_2 _252_ (
    .A(b[30]),
    .B(a[30]),
    .X(_036_)
  );
  sky130_fd_sc_hd__nor2_2 _253_ (
    .A(_000_),
    .B(_001_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_2 _254_ (
    .A(b[30]),
    .B(a[30]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__or2_2 _255_ (
    .A(b[29]),
    .B(a[29]),
    .X(_039_)
  );
  sky130_fd_sc_hd__nand2_2 _256_ (
    .A(b[29]),
    .B(a[29]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__or2_2 _257_ (
    .A(b[28]),
    .B(a[28]),
    .X(_041_)
  );
  sky130_fd_sc_hd__nand2_2 _258_ (
    .A(b[28]),
    .B(a[28]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__or2_2 _259_ (
    .A(b[27]),
    .B(a[27]),
    .X(_043_)
  );
  sky130_fd_sc_hd__nand2_2 _260_ (
    .A(b[27]),
    .B(a[27]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__or2_2 _261_ (
    .A(b[26]),
    .B(a[26]),
    .X(_045_)
  );
  sky130_fd_sc_hd__nand2_2 _262_ (
    .A(b[26]),
    .B(a[26]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__or2_2 _263_ (
    .A(b[25]),
    .B(a[25]),
    .X(_047_)
  );
  sky130_fd_sc_hd__nand2_2 _264_ (
    .A(b[25]),
    .B(a[25]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__or2_2 _265_ (
    .A(b[24]),
    .B(a[24]),
    .X(_049_)
  );
  sky130_fd_sc_hd__nand2_2 _266_ (
    .A(b[24]),
    .B(a[24]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_2 _267_ (
    .A(b[23]),
    .B(a[23]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__or2_2 _268_ (
    .A(b[22]),
    .B(a[22]),
    .X(_052_)
  );
  sky130_fd_sc_hd__nand2_2 _269_ (
    .A(b[22]),
    .B(a[22]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__or2_2 _270_ (
    .A(b[21]),
    .B(a[21]),
    .X(_054_)
  );
  sky130_fd_sc_hd__nand2_2 _271_ (
    .A(b[21]),
    .B(a[21]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__or2_2 _272_ (
    .A(b[19]),
    .B(a[19]),
    .X(_056_)
  );
  sky130_fd_sc_hd__nand2_2 _273_ (
    .A(b[19]),
    .B(a[19]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor2_2 _274_ (
    .A(b[18]),
    .B(a[18]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__or2_2 _275_ (
    .A(b[17]),
    .B(a[17]),
    .X(_059_)
  );
  sky130_fd_sc_hd__nand2_2 _276_ (
    .A(b[17]),
    .B(a[17]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__or2_2 _277_ (
    .A(b[16]),
    .B(a[16]),
    .X(_061_)
  );
  sky130_fd_sc_hd__nand2_2 _278_ (
    .A(b[16]),
    .B(a[16]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__or2_2 _279_ (
    .A(b[14]),
    .B(a[14]),
    .X(_063_)
  );
  sky130_fd_sc_hd__nand2_2 _280_ (
    .A(b[14]),
    .B(a[14]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__or2_2 _281_ (
    .A(b[13]),
    .B(a[13]),
    .X(_065_)
  );
  sky130_fd_sc_hd__nor2_2 _282_ (
    .A(_018_),
    .B(_019_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_2 _283_ (
    .A(b[13]),
    .B(a[13]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__or2_2 _284_ (
    .A(b[12]),
    .B(a[12]),
    .X(_068_)
  );
  sky130_fd_sc_hd__nand2_2 _285_ (
    .A(b[12]),
    .B(a[12]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__or2_2 _286_ (
    .A(b[11]),
    .B(a[11]),
    .X(_070_)
  );
  sky130_fd_sc_hd__nand2_2 _287_ (
    .A(b[11]),
    .B(a[11]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__or2_2 _288_ (
    .A(b[9]),
    .B(a[9]),
    .X(_072_)
  );
  sky130_fd_sc_hd__nand2_2 _289_ (
    .A(b[9]),
    .B(a[9]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__or2_2 _290_ (
    .A(b[8]),
    .B(a[8]),
    .X(_074_)
  );
  sky130_fd_sc_hd__nand2_2 _291_ (
    .A(b[8]),
    .B(a[8]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__or2_2 _292_ (
    .A(b[7]),
    .B(a[7]),
    .X(_076_)
  );
  sky130_fd_sc_hd__nand2_2 _293_ (
    .A(b[7]),
    .B(a[7]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_2 _294_ (
    .A(b[5]),
    .B(a[5]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__or2_2 _295_ (
    .A(b[4]),
    .B(a[4]),
    .X(_079_)
  );
  sky130_fd_sc_hd__nor2_2 _296_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_2 _297_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_2 _298_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__or2_2 _299_ (
    .A(b[1]),
    .B(a[1]),
    .X(_083_)
  );
  sky130_fd_sc_hd__nand2_2 _300_ (
    .A(a[0]),
    .B(cin),
    .Y(_084_)
  );
  sky130_fd_sc_hd__or2_2 _301_ (
    .A(a[0]),
    .B(cin),
    .X(_085_)
  );
  sky130_fd_sc_hd__o21ai_2 _302_ (
    .A1(a[0]),
    .A2(cin),
    .B1(b[0]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__and2_2 _303_ (
    .A(_084_),
    .B(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__nand3_2 _304_ (
    .A(_082_),
    .B(_084_),
    .C(_086_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o21ai_2 _305_ (
    .A1(b[1]),
    .A2(a[1]),
    .B1(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o22a_2 _306_ (
    .A1(b[2]),
    .A2(a[2]),
    .B1(b[1]),
    .B2(a[1]),
    .X(_090_)
  );
  sky130_fd_sc_hd__nand2_2 _307_ (
    .A(_088_),
    .B(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a22oi_2 _308_ (
    .A1(b[2]),
    .A2(a[2]),
    .B1(_088_),
    .B2(_090_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o211ai_2 _309_ (
    .A1(_030_),
    .A2(_031_),
    .B1(_081_),
    .C1(_091_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o21ai_2 _310_ (
    .A1(_080_),
    .A2(_092_),
    .B1(_081_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__o221ai_2 _311_ (
    .A1(_028_),
    .A2(_029_),
    .B1(_080_),
    .B2(_092_),
    .C1(_081_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__o221ai_2 _312_ (
    .A1(b[4]),
    .A2(a[4]),
    .B1(b[3]),
    .B2(a[3]),
    .C1(_093_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o21ai_2 _313_ (
    .A1(b[4]),
    .A2(a[4]),
    .B1(_095_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o211ai_2 _314_ (
    .A1(_028_),
    .A2(_029_),
    .B1(_078_),
    .C1(_096_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__o211ai_2 _315_ (
    .A1(b[5]),
    .A2(a[5]),
    .B1(_079_),
    .C1(_095_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o21ai_2 _316_ (
    .A1(b[5]),
    .A2(a[5]),
    .B1(_098_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o211ai_2 _317_ (
    .A1(_026_),
    .A2(_027_),
    .B1(_078_),
    .C1(_099_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o221ai_2 _318_ (
    .A1(b[6]),
    .A2(a[6]),
    .B1(b[5]),
    .B2(a[5]),
    .C1(_098_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__o21ai_2 _319_ (
    .A1(b[6]),
    .A2(a[6]),
    .B1(_101_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o211ai_2 _320_ (
    .A1(_026_),
    .A2(_027_),
    .B1(_077_),
    .C1(_102_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o211ai_2 _321_ (
    .A1(b[6]),
    .A2(a[6]),
    .B1(_076_),
    .C1(_101_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o21ai_2 _322_ (
    .A1(b[7]),
    .A2(a[7]),
    .B1(_104_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__o211ai_2 _323_ (
    .A1(_024_),
    .A2(_025_),
    .B1(_077_),
    .C1(_105_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__o221ai_2 _324_ (
    .A1(b[8]),
    .A2(a[8]),
    .B1(b[7]),
    .B2(a[7]),
    .C1(_104_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o21ai_2 _325_ (
    .A1(_024_),
    .A2(_025_),
    .B1(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__o211ai_2 _326_ (
    .A1(_024_),
    .A2(_025_),
    .B1(_073_),
    .C1(_108_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o211ai_2 _327_ (
    .A1(b[8]),
    .A2(a[8]),
    .B1(_072_),
    .C1(_107_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__o21ai_2 _328_ (
    .A1(b[9]),
    .A2(a[9]),
    .B1(_110_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__o211ai_2 _329_ (
    .A1(_022_),
    .A2(_023_),
    .B1(_073_),
    .C1(_111_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__o221ai_2 _330_ (
    .A1(b[10]),
    .A2(a[10]),
    .B1(b[9]),
    .B2(a[9]),
    .C1(_110_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o21ai_2 _331_ (
    .A1(b[10]),
    .A2(a[10]),
    .B1(_113_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o221ai_2 _332_ (
    .A1(_020_),
    .A2(_021_),
    .B1(_022_),
    .B2(_023_),
    .C1(_114_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o211ai_2 _333_ (
    .A1(b[10]),
    .A2(a[10]),
    .B1(_070_),
    .C1(_113_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__o21ai_2 _334_ (
    .A1(_020_),
    .A2(_021_),
    .B1(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__o211ai_2 _335_ (
    .A1(_020_),
    .A2(_021_),
    .B1(_069_),
    .C1(_117_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o221ai_2 _336_ (
    .A1(b[12]),
    .A2(a[12]),
    .B1(b[11]),
    .B2(a[11]),
    .C1(_116_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__o21ai_2 _337_ (
    .A1(b[12]),
    .A2(a[12]),
    .B1(_119_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o211ai_2 _338_ (
    .A1(_018_),
    .A2(_019_),
    .B1(_069_),
    .C1(_120_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__o221a_2 _339_ (
    .A1(b[13]),
    .A2(a[13]),
    .B1(b[12]),
    .B2(a[12]),
    .C1(_119_),
    .X(_123_)
  );
  sky130_fd_sc_hd__o211ai_2 _340_ (
    .A1(b[12]),
    .A2(a[12]),
    .B1(_065_),
    .C1(_119_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o211ai_2 _341_ (
    .A1(_018_),
    .A2(_019_),
    .B1(_064_),
    .C1(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o221ai_2 _342_ (
    .A1(b[14]),
    .A2(a[14]),
    .B1(b[13]),
    .B2(a[13]),
    .C1(_122_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o21ai_2 _343_ (
    .A1(b[14]),
    .A2(a[14]),
    .B1(_125_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o211ai_2 _344_ (
    .A1(_016_),
    .A2(_017_),
    .B1(_064_),
    .C1(_126_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o211ai_2 _345_ (
    .A1(b[15]),
    .A2(a[15]),
    .B1(_063_),
    .C1(_125_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o21ai_2 _346_ (
    .A1(_016_),
    .A2(_017_),
    .B1(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o211ai_2 _347_ (
    .A1(_016_),
    .A2(_017_),
    .B1(_062_),
    .C1(_129_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o221ai_2 _348_ (
    .A1(b[16]),
    .A2(a[16]),
    .B1(b[15]),
    .B2(a[15]),
    .C1(_128_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o21ai_2 _349_ (
    .A1(_014_),
    .A2(_015_),
    .B1(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o211ai_2 _350_ (
    .A1(_014_),
    .A2(_015_),
    .B1(_060_),
    .C1(_132_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o211ai_2 _351_ (
    .A1(b[16]),
    .A2(a[16]),
    .B1(_059_),
    .C1(_131_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o21ai_2 _352_ (
    .A1(b[17]),
    .A2(a[17]),
    .B1(_134_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__o211ai_2 _353_ (
    .A1(_012_),
    .A2(_013_),
    .B1(_060_),
    .C1(_135_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__o221ai_2 _354_ (
    .A1(b[18]),
    .A2(a[18]),
    .B1(b[17]),
    .B2(a[17]),
    .C1(_134_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__o21ai_2 _355_ (
    .A1(_012_),
    .A2(_013_),
    .B1(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o21ai_2 _356_ (
    .A1(b[18]),
    .A2(a[18]),
    .B1(_137_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o211ai_2 _357_ (
    .A1(_012_),
    .A2(_013_),
    .B1(_057_),
    .C1(_138_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o211ai_2 _358_ (
    .A1(b[18]),
    .A2(a[18]),
    .B1(_056_),
    .C1(_137_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__o21ai_2 _359_ (
    .A1(b[19]),
    .A2(a[19]),
    .B1(_141_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o211ai_2 _360_ (
    .A1(_010_),
    .A2(_011_),
    .B1(_057_),
    .C1(_142_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o221ai_2 _361_ (
    .A1(b[20]),
    .A2(a[20]),
    .B1(b[19]),
    .B2(a[19]),
    .C1(_141_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_2 _362_ (
    .A1(_010_),
    .A2(_011_),
    .B1(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o221ai_2 _363_ (
    .A1(_008_),
    .A2(_009_),
    .B1(_010_),
    .B2(_011_),
    .C1(_145_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o211ai_2 _364_ (
    .A1(b[20]),
    .A2(a[20]),
    .B1(_054_),
    .C1(_144_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o21ai_2 _365_ (
    .A1(_008_),
    .A2(_009_),
    .B1(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o211ai_2 _366_ (
    .A1(_008_),
    .A2(_009_),
    .B1(_053_),
    .C1(_148_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o221ai_2 _367_ (
    .A1(b[22]),
    .A2(a[22]),
    .B1(b[21]),
    .B2(a[21]),
    .C1(_147_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o21ai_2 _368_ (
    .A1(b[22]),
    .A2(a[22]),
    .B1(_150_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o211ai_2 _369_ (
    .A1(_006_),
    .A2(_007_),
    .B1(_053_),
    .C1(_151_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o211ai_2 _370_ (
    .A1(b[23]),
    .A2(a[23]),
    .B1(_052_),
    .C1(_150_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__o21ai_2 _371_ (
    .A1(b[23]),
    .A2(a[23]),
    .B1(_153_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o211ai_2 _372_ (
    .A1(_006_),
    .A2(_007_),
    .B1(_050_),
    .C1(_154_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o221ai_2 _373_ (
    .A1(b[24]),
    .A2(a[24]),
    .B1(b[23]),
    .B2(a[23]),
    .C1(_153_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o21ai_2 _374_ (
    .A1(b[24]),
    .A2(a[24]),
    .B1(_156_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand3_2 _375_ (
    .A(_048_),
    .B(_050_),
    .C(_157_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o211ai_2 _376_ (
    .A1(b[24]),
    .A2(a[24]),
    .B1(_047_),
    .C1(_156_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__o211ai_2 _377_ (
    .A1(_004_),
    .A2(_005_),
    .B1(_048_),
    .C1(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o221ai_2 _378_ (
    .A1(b[26]),
    .A2(a[26]),
    .B1(b[25]),
    .B2(a[25]),
    .C1(_159_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__o21ai_2 _379_ (
    .A1(_004_),
    .A2(_005_),
    .B1(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o211ai_2 _380_ (
    .A1(_004_),
    .A2(_005_),
    .B1(_044_),
    .C1(_162_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__o211ai_2 _381_ (
    .A1(b[26]),
    .A2(a[26]),
    .B1(_043_),
    .C1(_161_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o21ai_2 _382_ (
    .A1(b[27]),
    .A2(a[27]),
    .B1(_164_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o211ai_2 _383_ (
    .A1(_002_),
    .A2(_003_),
    .B1(_044_),
    .C1(_165_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__o221ai_2 _384_ (
    .A1(b[28]),
    .A2(a[28]),
    .B1(b[27]),
    .B2(a[27]),
    .C1(_164_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__o211ai_2 _385_ (
    .A1(_002_),
    .A2(_003_),
    .B1(_040_),
    .C1(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o211ai_2 _386_ (
    .A1(b[28]),
    .A2(a[28]),
    .B1(_039_),
    .C1(_167_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__o211ai_2 _387_ (
    .A1(_000_),
    .A2(_001_),
    .B1(_040_),
    .C1(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a2bb2oi_2 _388_ (
    .A1_N(b[30]),
    .A2_N(a[30]),
    .B1(_040_),
    .B2(_170_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__o221ai_2 _389_ (
    .A1(b[30]),
    .A2(a[30]),
    .B1(b[29]),
    .B2(a[29]),
    .C1(_169_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__o221ai_2 _390_ (
    .A1(b[31]),
    .A2(a[31]),
    .B1(b[30]),
    .B2(a[30]),
    .C1(_171_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a31o_2 _391_ (
    .A1(_033_),
    .A2(_036_),
    .A3(_171_),
    .B1(_034_),
    .X(cout)
  );
  sky130_fd_sc_hd__o31a_2 _392_ (
    .A1(_034_),
    .A2(_037_),
    .A3(_172_),
    .B1(_174_),
    .X(overflow)
  );
  sky130_fd_sc_hd__and3_2 _393_ (
    .A(b[0]),
    .B(a[0]),
    .C(cin),
    .X(_175_)
  );
  sky130_fd_sc_hd__o22a_2 _394_ (
    .A1(_085_),
    .A2(b[0]),
    .B1(_175_),
    .B2(_087_),
    .X(\bit_adder[0].FA.sum )
  );
  sky130_fd_sc_hd__and3_2 _395_ (
    .A(_087_),
    .B(_083_),
    .C(_082_),
    .X(_176_)
  );
  sky130_fd_sc_hd__a21oi_2 _396_ (
    .A1(_082_),
    .A2(_083_),
    .B1(_087_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__or2_2 _397_ (
    .A(_176_),
    .B(_177_),
    .X(\bit_adder[1].FA.sum )
  );
  sky130_fd_sc_hd__xor2_2 _398_ (
    .A(b[2]),
    .B(a[2]),
    .X(_178_)
  );
  sky130_fd_sc_hd__xnor2_2 _399_ (
    .A(_089_),
    .B(_178_),
    .Y(\bit_adder[2].FA.sum )
  );
  sky130_fd_sc_hd__and2b_2 _400_ (
    .A_N(_080_),
    .B(_081_),
    .X(_179_)
  );
  sky130_fd_sc_hd__xnor2_2 _401_ (
    .A(_092_),
    .B(_179_),
    .Y(\bit_adder[3].FA.sum )
  );
  sky130_fd_sc_hd__and3_2 _402_ (
    .A(b[4]),
    .B(a[4]),
    .C(_094_),
    .X(_180_)
  );
  sky130_fd_sc_hd__o22a_2 _403_ (
    .A1(_079_),
    .A2(_094_),
    .B1(_097_),
    .B2(_180_),
    .X(\bit_adder[4].FA.sum )
  );
  sky130_fd_sc_hd__a211o_2 _404_ (
    .A1(_079_),
    .A2(_095_),
    .B1(b[5]),
    .C1(a[5]),
    .X(_181_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _405_ (
    .A1_N(_078_),
    .A2_N(_097_),
    .B1(_100_),
    .B2(_181_),
    .X(\bit_adder[5].FA.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _406_ (
    .A(b[6]),
    .B(a[6]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__xor2_2 _407_ (
    .A(_100_),
    .B(_182_),
    .X(\bit_adder[6].FA.sum )
  );
  sky130_fd_sc_hd__a21oi_2 _408_ (
    .A1(_076_),
    .A2(_077_),
    .B1(_103_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__and3_2 _409_ (
    .A(_076_),
    .B(_077_),
    .C(_103_),
    .X(_184_)
  );
  sky130_fd_sc_hd__or2_2 _410_ (
    .A(_183_),
    .B(_184_),
    .X(\bit_adder[7].FA.sum )
  );
  sky130_fd_sc_hd__a21oi_2 _411_ (
    .A1(_074_),
    .A2(_075_),
    .B1(_106_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__and3_2 _412_ (
    .A(_074_),
    .B(_075_),
    .C(_106_),
    .X(_186_)
  );
  sky130_fd_sc_hd__or2_2 _413_ (
    .A(_185_),
    .B(_186_),
    .X(\bit_adder[8].FA.sum )
  );
  sky130_fd_sc_hd__and3_2 _414_ (
    .A(b[9]),
    .B(a[9]),
    .C(_109_),
    .X(_187_)
  );
  sky130_fd_sc_hd__o22a_2 _415_ (
    .A1(_072_),
    .A2(_109_),
    .B1(_112_),
    .B2(_187_),
    .X(\bit_adder[9].FA.sum )
  );
  sky130_fd_sc_hd__xor2_2 _416_ (
    .A(b[10]),
    .B(a[10]),
    .X(_188_)
  );
  sky130_fd_sc_hd__xnor2_2 _417_ (
    .A(_112_),
    .B(_188_),
    .Y(\bit_adder[10].FA.sum )
  );
  sky130_fd_sc_hd__nand2_2 _418_ (
    .A(_070_),
    .B(_071_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__xor2_2 _419_ (
    .A(_115_),
    .B(_189_),
    .X(\bit_adder[11].FA.sum )
  );
  sky130_fd_sc_hd__nand2_2 _420_ (
    .A(_068_),
    .B(_069_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__xnor2_2 _421_ (
    .A(_118_),
    .B(_190_),
    .Y(\bit_adder[12].FA.sum )
  );
  sky130_fd_sc_hd__nand2_2 _422_ (
    .A(_065_),
    .B(_067_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__xor2_2 _423_ (
    .A(_121_),
    .B(_191_),
    .X(\bit_adder[13].FA.sum )
  );
  sky130_fd_sc_hd__and4_2 _424_ (
    .A(_122_),
    .B(a[14]),
    .C(b[14]),
    .D(_065_),
    .X(_192_)
  );
  sky130_fd_sc_hd__o32a_2 _425_ (
    .A1(_063_),
    .A2(_066_),
    .A3(_123_),
    .B1(_192_),
    .B2(_127_),
    .X(\bit_adder[14].FA.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _426_ (
    .A(b[15]),
    .B(a[15]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__xor2_2 _427_ (
    .A(_127_),
    .B(_193_),
    .X(\bit_adder[15].FA.sum )
  );
  sky130_fd_sc_hd__nand2_2 _428_ (
    .A(_061_),
    .B(_062_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__xnor2_2 _429_ (
    .A(_130_),
    .B(_194_),
    .Y(\bit_adder[16].FA.sum )
  );
  sky130_fd_sc_hd__nand2_2 _430_ (
    .A(_059_),
    .B(_060_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__xnor2_2 _431_ (
    .A(_133_),
    .B(_195_),
    .Y(\bit_adder[17].FA.sum )
  );
  sky130_fd_sc_hd__and4_2 _432_ (
    .A(_134_),
    .B(a[18]),
    .C(b[18]),
    .D(_059_),
    .X(_196_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _433_ (
    .A1_N(_058_),
    .A2_N(_136_),
    .B1(_196_),
    .B2(_140_),
    .X(\bit_adder[18].FA.sum )
  );
  sky130_fd_sc_hd__and3_2 _434_ (
    .A(b[19]),
    .B(a[19]),
    .C(_139_),
    .X(_197_)
  );
  sky130_fd_sc_hd__o22a_2 _435_ (
    .A1(_056_),
    .A2(_139_),
    .B1(_143_),
    .B2(_197_),
    .X(\bit_adder[19].FA.sum )
  );
  sky130_fd_sc_hd__xnor2_2 _436_ (
    .A(b[20]),
    .B(a[20]),
    .Y(_198_)
  );
  sky130_fd_sc_hd__xor2_2 _437_ (
    .A(_143_),
    .B(_198_),
    .X(\bit_adder[20].FA.sum )
  );
  sky130_fd_sc_hd__a21oi_2 _438_ (
    .A1(_054_),
    .A2(_055_),
    .B1(_146_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__and3_2 _439_ (
    .A(_146_),
    .B(_055_),
    .C(_054_),
    .X(_200_)
  );
  sky130_fd_sc_hd__nor2_2 _440_ (
    .A(_199_),
    .B(_200_),
    .Y(\bit_adder[21].FA.sum )
  );
  sky130_fd_sc_hd__and3_2 _441_ (
    .A(b[22]),
    .B(a[22]),
    .C(_149_),
    .X(_201_)
  );
  sky130_fd_sc_hd__o22a_2 _442_ (
    .A1(_052_),
    .A2(_149_),
    .B1(_201_),
    .B2(_152_),
    .X(\bit_adder[22].FA.sum )
  );
  sky130_fd_sc_hd__or3b_2 _443_ (
    .A(b[23]),
    .B(a[23]),
    .C_N(_152_),
    .X(_202_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _444_ (
    .A1_N(_051_),
    .A2_N(_152_),
    .B1(_155_),
    .B2(_202_),
    .X(\bit_adder[23].FA.sum )
  );
  sky130_fd_sc_hd__and2_2 _445_ (
    .A(_049_),
    .B(_050_),
    .X(_203_)
  );
  sky130_fd_sc_hd__xnor2_2 _446_ (
    .A(_155_),
    .B(_203_),
    .Y(\bit_adder[24].FA.sum )
  );
  sky130_fd_sc_hd__nand2_2 _447_ (
    .A(_047_),
    .B(_048_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__xor2_2 _448_ (
    .A(_158_),
    .B(_204_),
    .X(\bit_adder[25].FA.sum )
  );
  sky130_fd_sc_hd__a22oi_2 _449_ (
    .A1(_045_),
    .A2(_046_),
    .B1(_047_),
    .B2(_159_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__and4_2 _450_ (
    .A(_045_),
    .B(_046_),
    .C(_047_),
    .D(_159_),
    .X(_206_)
  );
  sky130_fd_sc_hd__nor2_2 _451_ (
    .A(_205_),
    .B(_206_),
    .Y(\bit_adder[26].FA.sum )
  );
  sky130_fd_sc_hd__and3_2 _452_ (
    .A(b[27]),
    .B(a[27]),
    .C(_163_),
    .X(_207_)
  );
  sky130_fd_sc_hd__o22a_2 _453_ (
    .A1(_043_),
    .A2(_163_),
    .B1(_166_),
    .B2(_207_),
    .X(\bit_adder[27].FA.sum )
  );
  sky130_fd_sc_hd__a21oi_2 _454_ (
    .A1(_041_),
    .A2(_042_),
    .B1(_166_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__and3_2 _455_ (
    .A(_041_),
    .B(_042_),
    .C(_166_),
    .X(_209_)
  );
  sky130_fd_sc_hd__or2_2 _456_ (
    .A(_208_),
    .B(_209_),
    .X(\bit_adder[28].FA.sum )
  );
  sky130_fd_sc_hd__a22oi_2 _457_ (
    .A1(_039_),
    .A2(_040_),
    .B1(_041_),
    .B2(_167_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__and4_2 _458_ (
    .A(_039_),
    .B(_040_),
    .C(_041_),
    .D(_167_),
    .X(_211_)
  );
  sky130_fd_sc_hd__nor2_2 _459_ (
    .A(_210_),
    .B(_211_),
    .Y(\bit_adder[29].FA.sum )
  );
  sky130_fd_sc_hd__a22o_2 _460_ (
    .A1(_036_),
    .A2(_038_),
    .B1(_040_),
    .B2(_170_),
    .X(_212_)
  );
  sky130_fd_sc_hd__nand4_2 _461_ (
    .A(_036_),
    .B(_038_),
    .C(_040_),
    .D(_170_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nand2_2 _462_ (
    .A(_212_),
    .B(_213_),
    .Y(\bit_adder[30].FA.sum )
  );
  sky130_fd_sc_hd__o221ai_2 _463_ (
    .A1(b[30]),
    .A2(a[30]),
    .B1(_032_),
    .B2(_034_),
    .C1(_171_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__o2111ai_2 _464_ (
    .A1(_000_),
    .A2(_001_),
    .B1(_033_),
    .C1(_035_),
    .D1(_173_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nand2_2 _465_ (
    .A(_214_),
    .B(_215_),
    .Y(\bit_adder[31].FA.sum )
  );
  sky130_fd_sc_hd__buf_2 _466_ (
    .A(\bit_adder[18].FA.sum ),
    .X(sum[18])
  );
  sky130_fd_sc_hd__buf_2 _467_ (
    .A(\bit_adder[19].FA.sum ),
    .X(sum[19])
  );
  sky130_fd_sc_hd__buf_2 _468_ (
    .A(\bit_adder[20].FA.sum ),
    .X(sum[20])
  );
  sky130_fd_sc_hd__buf_2 _469_ (
    .A(\bit_adder[21].FA.sum ),
    .X(sum[21])
  );
  sky130_fd_sc_hd__buf_2 _470_ (
    .A(\bit_adder[22].FA.sum ),
    .X(sum[22])
  );
  sky130_fd_sc_hd__buf_2 _471_ (
    .A(\bit_adder[23].FA.sum ),
    .X(sum[23])
  );
  sky130_fd_sc_hd__buf_2 _472_ (
    .A(\bit_adder[24].FA.sum ),
    .X(sum[24])
  );
  sky130_fd_sc_hd__buf_2 _473_ (
    .A(\bit_adder[25].FA.sum ),
    .X(sum[25])
  );
  sky130_fd_sc_hd__buf_2 _474_ (
    .A(\bit_adder[26].FA.sum ),
    .X(sum[26])
  );
  sky130_fd_sc_hd__buf_2 _475_ (
    .A(\bit_adder[27].FA.sum ),
    .X(sum[27])
  );
  sky130_fd_sc_hd__buf_2 _476_ (
    .A(\bit_adder[28].FA.sum ),
    .X(sum[28])
  );
  sky130_fd_sc_hd__buf_2 _477_ (
    .A(\bit_adder[29].FA.sum ),
    .X(sum[29])
  );
  sky130_fd_sc_hd__buf_2 _478_ (
    .A(\bit_adder[30].FA.sum ),
    .X(sum[30])
  );
  sky130_fd_sc_hd__buf_2 _479_ (
    .A(\bit_adder[31].FA.sum ),
    .X(sum[31])
  );
  sky130_fd_sc_hd__buf_2 _480_ (
    .A(\bit_adder[0].FA.sum ),
    .X(sum[0])
  );
  sky130_fd_sc_hd__buf_2 _481_ (
    .A(\bit_adder[1].FA.sum ),
    .X(sum[1])
  );
  sky130_fd_sc_hd__buf_2 _482_ (
    .A(\bit_adder[2].FA.sum ),
    .X(sum[2])
  );
  sky130_fd_sc_hd__buf_2 _483_ (
    .A(\bit_adder[3].FA.sum ),
    .X(sum[3])
  );
  sky130_fd_sc_hd__buf_2 _484_ (
    .A(\bit_adder[4].FA.sum ),
    .X(sum[4])
  );
  sky130_fd_sc_hd__buf_2 _485_ (
    .A(\bit_adder[5].FA.sum ),
    .X(sum[5])
  );
  sky130_fd_sc_hd__buf_2 _486_ (
    .A(\bit_adder[6].FA.sum ),
    .X(sum[6])
  );
  sky130_fd_sc_hd__buf_2 _487_ (
    .A(\bit_adder[7].FA.sum ),
    .X(sum[7])
  );
  sky130_fd_sc_hd__buf_2 _488_ (
    .A(\bit_adder[8].FA.sum ),
    .X(sum[8])
  );
  sky130_fd_sc_hd__buf_2 _489_ (
    .A(\bit_adder[9].FA.sum ),
    .X(sum[9])
  );
  sky130_fd_sc_hd__buf_2 _490_ (
    .A(\bit_adder[10].FA.sum ),
    .X(sum[10])
  );
  sky130_fd_sc_hd__buf_2 _491_ (
    .A(\bit_adder[11].FA.sum ),
    .X(sum[11])
  );
  sky130_fd_sc_hd__buf_2 _492_ (
    .A(\bit_adder[12].FA.sum ),
    .X(sum[12])
  );
  sky130_fd_sc_hd__buf_2 _493_ (
    .A(\bit_adder[13].FA.sum ),
    .X(sum[13])
  );
  sky130_fd_sc_hd__buf_2 _494_ (
    .A(\bit_adder[14].FA.sum ),
    .X(sum[14])
  );
  sky130_fd_sc_hd__buf_2 _495_ (
    .A(\bit_adder[15].FA.sum ),
    .X(sum[15])
  );
  sky130_fd_sc_hd__buf_2 _496_ (
    .A(\bit_adder[16].FA.sum ),
    .X(sum[16])
  );
  sky130_fd_sc_hd__buf_2 _497_ (
    .A(\bit_adder[17].FA.sum ),
    .X(sum[17])
  );
endmodule
