/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module carry_bypass_adder_synthesized(a, b, cin, clk, sum, cout, overflow);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  input [31:0] a;
  wire [31:0] a;
  input [31:0] b;
  wire [31:0] b;
  wire \carry_ripple[0].RA.full_adder[0].FA.out ;
  wire \carry_ripple[0].RA.full_adder[1].FA.out ;
  wire \carry_ripple[0].RA.full_adder[2].FA.out ;
  wire \carry_ripple[0].RA.full_adder[3].FA.out ;
  wire \carry_ripple[1].RA.full_adder[0].FA.out ;
  wire \carry_ripple[1].RA.full_adder[1].FA.out ;
  wire \carry_ripple[1].RA.full_adder[2].FA.out ;
  wire \carry_ripple[1].RA.full_adder[3].FA.out ;
  wire \carry_ripple[2].RA.full_adder[0].FA.out ;
  wire \carry_ripple[2].RA.full_adder[1].FA.out ;
  wire \carry_ripple[2].RA.full_adder[2].FA.out ;
  wire \carry_ripple[2].RA.full_adder[3].FA.out ;
  wire \carry_ripple[3].RA.full_adder[0].FA.out ;
  wire \carry_ripple[3].RA.full_adder[1].FA.out ;
  wire \carry_ripple[3].RA.full_adder[2].FA.out ;
  wire \carry_ripple[3].RA.full_adder[3].FA.out ;
  wire \carry_ripple[4].RA.full_adder[0].FA.out ;
  wire \carry_ripple[4].RA.full_adder[1].FA.out ;
  wire \carry_ripple[4].RA.full_adder[2].FA.out ;
  wire \carry_ripple[4].RA.full_adder[3].FA.out ;
  wire \carry_ripple[5].RA.full_adder[0].FA.out ;
  wire \carry_ripple[5].RA.full_adder[1].FA.out ;
  wire \carry_ripple[5].RA.full_adder[2].FA.out ;
  wire \carry_ripple[5].RA.full_adder[3].FA.out ;
  wire \carry_ripple[6].RA.full_adder[0].FA.out ;
  wire \carry_ripple[6].RA.full_adder[1].FA.out ;
  wire \carry_ripple[6].RA.full_adder[2].FA.out ;
  wire \carry_ripple[6].RA.full_adder[3].FA.out ;
  wire \carry_ripple[7].RA.full_adder[0].FA.out ;
  wire \carry_ripple[7].RA.full_adder[1].FA.out ;
  wire \carry_ripple[7].RA.full_adder[2].FA.out ;
  wire \carry_ripple[7].RA.full_adder[3].FA.out ;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output cout;
  wire cout;
  output overflow;
  wire overflow;
  output [31:0] sum;
  wire [31:0] sum;
  sky130_fd_sc_hd__inv_2 _194_ (
    .A(b[30]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__inv_2 _195_ (
    .A(a[30]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__inv_2 _196_ (
    .A(b[3]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__inv_2 _197_ (
    .A(a[3]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_2 _198_ (
    .A(b[1]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__inv_2 _199_ (
    .A(a[1]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_2 _200_ (
    .A(b[5]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__inv_2 _201_ (
    .A(a[5]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__inv_2 _202_ (
    .A(b[9]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__inv_2 _203_ (
    .A(a[9]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__inv_2 _204_ (
    .A(b[8]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__inv_2 _205_ (
    .A(a[8]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__inv_2 _206_ (
    .A(b[13]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__inv_2 _207_ (
    .A(a[13]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_2 _208_ (
    .A(b[17]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__inv_2 _209_ (
    .A(a[17]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_2 _210_ (
    .A(b[21]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_2 _211_ (
    .A(a[21]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__inv_2 _212_ (
    .A(b[25]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__inv_2 _213_ (
    .A(a[25]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor2_2 _214_ (
    .A(b[31]),
    .B(a[31]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__and2_2 _215_ (
    .A(b[31]),
    .B(a[31]),
    .X(_021_)
  );
  sky130_fd_sc_hd__nand2_2 _216_ (
    .A(b[31]),
    .B(a[31]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor2_2 _217_ (
    .A(_020_),
    .B(_021_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_2 _218_ (
    .A(_000_),
    .B(_001_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_2 _219_ (
    .A(b[30]),
    .B(a[30]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__or2_2 _220_ (
    .A(b[30]),
    .B(a[30]),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2_2 _221_ (
    .A(b[29]),
    .B(a[29]),
    .X(_027_)
  );
  sky130_fd_sc_hd__nand2_2 _222_ (
    .A(b[29]),
    .B(a[29]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__or2_2 _223_ (
    .A(b[29]),
    .B(a[29]),
    .X(_029_)
  );
  sky130_fd_sc_hd__and2_2 _224_ (
    .A(b[28]),
    .B(a[28]),
    .X(_030_)
  );
  sky130_fd_sc_hd__nor2_2 _225_ (
    .A(b[28]),
    .B(a[28]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__or2_2 _226_ (
    .A(b[28]),
    .B(a[28]),
    .X(_032_)
  );
  sky130_fd_sc_hd__nor2_2 _227_ (
    .A(b[24]),
    .B(a[24]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__and2_2 _228_ (
    .A(b[24]),
    .B(a[24]),
    .X(_034_)
  );
  sky130_fd_sc_hd__nor2_2 _229_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__or2_2 _230_ (
    .A(b[26]),
    .B(a[26]),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2_2 _231_ (
    .A(b[26]),
    .B(a[26]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__and2_2 _232_ (
    .A(_036_),
    .B(_037_),
    .X(_038_)
  );
  sky130_fd_sc_hd__xor2_2 _233_ (
    .A(b[25]),
    .B(a[25]),
    .X(_039_)
  );
  sky130_fd_sc_hd__xor2_2 _234_ (
    .A(b[27]),
    .B(a[27]),
    .X(_040_)
  );
  sky130_fd_sc_hd__nand4_2 _235_ (
    .A(_035_),
    .B(_038_),
    .C(_039_),
    .D(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_2 _236_ (
    .A(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor2_2 _237_ (
    .A(b[20]),
    .B(a[20]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__and2_2 _238_ (
    .A(b[20]),
    .B(a[20]),
    .X(_044_)
  );
  sky130_fd_sc_hd__nor2_2 _239_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__or2_2 _240_ (
    .A(b[22]),
    .B(a[22]),
    .X(_046_)
  );
  sky130_fd_sc_hd__nand2_2 _241_ (
    .A(b[22]),
    .B(a[22]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__and2_2 _242_ (
    .A(_046_),
    .B(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__xor2_2 _243_ (
    .A(b[21]),
    .B(a[21]),
    .X(_049_)
  );
  sky130_fd_sc_hd__xor2_2 _244_ (
    .A(b[23]),
    .B(a[23]),
    .X(_050_)
  );
  sky130_fd_sc_hd__nand4_2 _245_ (
    .A(_045_),
    .B(_048_),
    .C(_049_),
    .D(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__inv_2 _246_ (
    .A(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor2_2 _247_ (
    .A(b[16]),
    .B(a[16]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__and2_2 _248_ (
    .A(b[16]),
    .B(a[16]),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor2_2 _249_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__or2_2 _250_ (
    .A(b[18]),
    .B(a[18]),
    .X(_056_)
  );
  sky130_fd_sc_hd__nand2_2 _251_ (
    .A(b[18]),
    .B(a[18]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__and2_2 _252_ (
    .A(_056_),
    .B(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__xor2_2 _253_ (
    .A(b[17]),
    .B(a[17]),
    .X(_059_)
  );
  sky130_fd_sc_hd__xor2_2 _254_ (
    .A(b[19]),
    .B(a[19]),
    .X(_060_)
  );
  sky130_fd_sc_hd__and4_2 _255_ (
    .A(_055_),
    .B(_058_),
    .C(_059_),
    .D(_060_),
    .X(_061_)
  );
  sky130_fd_sc_hd__or2_2 _256_ (
    .A(b[14]),
    .B(a[14]),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand2_2 _257_ (
    .A(b[14]),
    .B(a[14]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__and2_2 _258_ (
    .A(b[12]),
    .B(a[12]),
    .X(_064_)
  );
  sky130_fd_sc_hd__or2_2 _259_ (
    .A(b[6]),
    .B(a[6]),
    .X(_065_)
  );
  sky130_fd_sc_hd__nand2_2 _260_ (
    .A(b[6]),
    .B(a[6]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__and2_2 _261_ (
    .A(_065_),
    .B(_066_),
    .X(_067_)
  );
  sky130_fd_sc_hd__or2_2 _262_ (
    .A(b[4]),
    .B(a[4]),
    .X(_068_)
  );
  sky130_fd_sc_hd__nand2_2 _263_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__and2_2 _264_ (
    .A(_068_),
    .B(_069_),
    .X(_070_)
  );
  sky130_fd_sc_hd__xor2_2 _265_ (
    .A(b[7]),
    .B(a[7]),
    .X(_071_)
  );
  sky130_fd_sc_hd__nor2_2 _266_ (
    .A(b[5]),
    .B(a[5]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_2 _267_ (
    .A(_006_),
    .B(_007_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_2 _268_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand4_2 _269_ (
    .A(_067_),
    .B(_070_),
    .C(_071_),
    .D(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__inv_2 _270_ (
    .A(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__or2_2 _271_ (
    .A(b[3]),
    .B(a[3]),
    .X(_077_)
  );
  sky130_fd_sc_hd__nand2_2 _272_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_2 _273_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_2 _274_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__or2_2 _275_ (
    .A(b[0]),
    .B(a[0]),
    .X(_081_)
  );
  sky130_fd_sc_hd__a21o_2 _276_ (
    .A1(b[0]),
    .A2(a[0]),
    .B1(cin),
    .X(_082_)
  );
  sky130_fd_sc_hd__o21a_2 _277_ (
    .A1(b[0]),
    .A2(a[0]),
    .B1(cin),
    .X(_083_)
  );
  sky130_fd_sc_hd__o21ai_2 _278_ (
    .A1(b[0]),
    .A2(a[0]),
    .B1(_082_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a221o_2 _279_ (
    .A1(b[1]),
    .A2(a[1]),
    .B1(b[0]),
    .B2(a[0]),
    .C1(_083_),
    .X(_085_)
  );
  sky130_fd_sc_hd__o221ai_2 _280_ (
    .A1(b[1]),
    .A2(a[1]),
    .B1(b[0]),
    .B2(a[0]),
    .C1(_082_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o21a_2 _281_ (
    .A1(_004_),
    .A2(_005_),
    .B1(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__o211ai_2 _282_ (
    .A1(_004_),
    .A2(_005_),
    .B1(_080_),
    .C1(_086_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o21ai_2 _283_ (
    .A1(b[2]),
    .A2(a[2]),
    .B1(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o211ai_2 _284_ (
    .A1(b[2]),
    .A2(a[2]),
    .B1(_077_),
    .C1(_088_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o21a_2 _285_ (
    .A1(_002_),
    .A2(_003_),
    .B1(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd__nand2_2 _286_ (
    .A(_076_),
    .B(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o211ai_2 _287_ (
    .A1(_002_),
    .A2(_003_),
    .B1(_069_),
    .C1(_090_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o211ai_2 _288_ (
    .A1(b[5]),
    .A2(a[5]),
    .B1(_068_),
    .C1(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a22o_2 _289_ (
    .A1(b[5]),
    .A2(a[5]),
    .B1(_068_),
    .B2(_093_),
    .X(_095_)
  );
  sky130_fd_sc_hd__o21a_2 _290_ (
    .A1(_006_),
    .A2(_007_),
    .B1(_094_),
    .X(_096_)
  );
  sky130_fd_sc_hd__o211ai_2 _291_ (
    .A1(_006_),
    .A2(_007_),
    .B1(_066_),
    .C1(_094_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o21ai_2 _292_ (
    .A1(b[6]),
    .A2(a[6]),
    .B1(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__o211ai_2 _293_ (
    .A1(b[7]),
    .A2(a[7]),
    .B1(_065_),
    .C1(_097_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a21oi_2 _294_ (
    .A1(b[7]),
    .A2(a[7]),
    .B1(_076_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_2 _295_ (
    .A(_099_),
    .B(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a22o_2 _296_ (
    .A1(_076_),
    .A2(_091_),
    .B1(_099_),
    .B2(_100_),
    .X(_102_)
  );
  sky130_fd_sc_hd__xor2_2 _297_ (
    .A(b[8]),
    .B(a[8]),
    .X(_103_)
  );
  sky130_fd_sc_hd__or2_2 _298_ (
    .A(b[10]),
    .B(a[10]),
    .X(_104_)
  );
  sky130_fd_sc_hd__nand2_2 _299_ (
    .A(b[10]),
    .B(a[10]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__and2_2 _300_ (
    .A(_104_),
    .B(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__xor2_2 _301_ (
    .A(b[9]),
    .B(a[9]),
    .X(_107_)
  );
  sky130_fd_sc_hd__xor2_2 _302_ (
    .A(b[11]),
    .B(a[11]),
    .X(_108_)
  );
  sky130_fd_sc_hd__nand4_2 _303_ (
    .A(_103_),
    .B(_106_),
    .C(_107_),
    .D(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__inv_2 _304_ (
    .A(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a2bb2oi_2 _305_ (
    .A1_N(_010_),
    .A2_N(_011_),
    .B1(_092_),
    .B2(_101_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a22o_2 _306_ (
    .A1(_008_),
    .A2(_009_),
    .B1(_010_),
    .B2(_011_),
    .X(_112_)
  );
  sky130_fd_sc_hd__o22a_2 _307_ (
    .A1(_008_),
    .A2(_009_),
    .B1(_112_),
    .B2(_111_),
    .X(_113_)
  );
  sky130_fd_sc_hd__o221ai_2 _308_ (
    .A1(_008_),
    .A2(_009_),
    .B1(_112_),
    .B2(_111_),
    .C1(_105_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o21ai_2 _309_ (
    .A1(b[10]),
    .A2(a[10]),
    .B1(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o211ai_2 _310_ (
    .A1(b[11]),
    .A2(a[11]),
    .B1(_104_),
    .C1(_114_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21oi_2 _311_ (
    .A1(b[11]),
    .A2(a[11]),
    .B1(_110_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a22oi_2 _312_ (
    .A1(_102_),
    .A2(_110_),
    .B1(_116_),
    .B2(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a22o_2 _313_ (
    .A1(_102_),
    .A2(_110_),
    .B1(_116_),
    .B2(_117_),
    .X(_119_)
  );
  sky130_fd_sc_hd__a21o_2 _314_ (
    .A1(b[12]),
    .A2(a[12]),
    .B1(_118_),
    .X(_120_)
  );
  sky130_fd_sc_hd__nor2_2 _315_ (
    .A(b[12]),
    .B(a[12]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a21o_2 _316_ (
    .A1(_012_),
    .A2(_013_),
    .B1(_121_),
    .X(_122_)
  );
  sky130_fd_sc_hd__o21bai_2 _317_ (
    .A1(_064_),
    .A2(_118_),
    .B1_N(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__o21a_2 _318_ (
    .A1(_012_),
    .A2(_013_),
    .B1(_123_),
    .X(_124_)
  );
  sky130_fd_sc_hd__o211ai_2 _319_ (
    .A1(_012_),
    .A2(_013_),
    .B1(_063_),
    .C1(_123_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o211ai_2 _320_ (
    .A1(b[15]),
    .A2(a[15]),
    .B1(_062_),
    .C1(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__xor2_2 _321_ (
    .A(b[13]),
    .B(a[13]),
    .X(_127_)
  );
  sky130_fd_sc_hd__nor2_2 _322_ (
    .A(_064_),
    .B(_121_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__xor2_2 _323_ (
    .A(b[15]),
    .B(a[15]),
    .X(_129_)
  );
  sky130_fd_sc_hd__and2_2 _324_ (
    .A(_062_),
    .B(_063_),
    .X(_130_)
  );
  sky130_fd_sc_hd__nand4_2 _325_ (
    .A(_127_),
    .B(_128_),
    .C(_129_),
    .D(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__inv_2 _326_ (
    .A(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_2 _327_ (
    .A1(b[15]),
    .A2(a[15]),
    .B1(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a22oi_2 _328_ (
    .A1(_119_),
    .A2(_132_),
    .B1(_126_),
    .B2(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a22o_2 _329_ (
    .A1(_119_),
    .A2(_132_),
    .B1(_126_),
    .B2(_133_),
    .X(_135_)
  );
  sky130_fd_sc_hd__a21o_2 _330_ (
    .A1(_014_),
    .A2(_015_),
    .B1(_053_),
    .X(_136_)
  );
  sky130_fd_sc_hd__o21bai_2 _331_ (
    .A1(_054_),
    .A2(_134_),
    .B1_N(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__o21a_2 _332_ (
    .A1(_014_),
    .A2(_015_),
    .B1(_137_),
    .X(_138_)
  );
  sky130_fd_sc_hd__o211ai_2 _333_ (
    .A1(_014_),
    .A2(_015_),
    .B1(_057_),
    .C1(_137_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o21ai_2 _334_ (
    .A1(b[18]),
    .A2(a[18]),
    .B1(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o211ai_2 _335_ (
    .A1(b[19]),
    .A2(a[19]),
    .B1(_056_),
    .C1(_139_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a21oi_2 _336_ (
    .A1(b[19]),
    .A2(a[19]),
    .B1(_061_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a22oi_2 _337_ (
    .A1(_061_),
    .A2(_135_),
    .B1(_141_),
    .B2(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a22o_2 _338_ (
    .A1(_061_),
    .A2(_135_),
    .B1(_141_),
    .B2(_142_),
    .X(_144_)
  );
  sky130_fd_sc_hd__a21o_2 _339_ (
    .A1(_016_),
    .A2(_017_),
    .B1(_043_),
    .X(_145_)
  );
  sky130_fd_sc_hd__o21bai_2 _340_ (
    .A1(_044_),
    .A2(_143_),
    .B1_N(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o21ai_2 _341_ (
    .A1(_016_),
    .A2(_017_),
    .B1(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o211ai_2 _342_ (
    .A1(_016_),
    .A2(_017_),
    .B1(_047_),
    .C1(_146_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o21ai_2 _343_ (
    .A1(b[22]),
    .A2(a[22]),
    .B1(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o211ai_2 _344_ (
    .A1(b[23]),
    .A2(a[23]),
    .B1(_046_),
    .C1(_148_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a21oi_2 _345_ (
    .A1(b[23]),
    .A2(a[23]),
    .B1(_052_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a22oi_2 _346_ (
    .A1(_052_),
    .A2(_144_),
    .B1(_150_),
    .B2(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__a22o_2 _347_ (
    .A1(_052_),
    .A2(_144_),
    .B1(_150_),
    .B2(_151_),
    .X(_153_)
  );
  sky130_fd_sc_hd__a21oi_2 _348_ (
    .A1(b[24]),
    .A2(a[24]),
    .B1(_152_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a21o_2 _349_ (
    .A1(_018_),
    .A2(_019_),
    .B1(_033_),
    .X(_155_)
  );
  sky130_fd_sc_hd__o21bai_2 _350_ (
    .A1(_034_),
    .A2(_152_),
    .B1_N(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o22a_2 _351_ (
    .A1(_018_),
    .A2(_019_),
    .B1(_155_),
    .B2(_154_),
    .X(_157_)
  );
  sky130_fd_sc_hd__o211ai_2 _352_ (
    .A1(_018_),
    .A2(_019_),
    .B1(_037_),
    .C1(_156_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o21ai_2 _353_ (
    .A1(b[26]),
    .A2(a[26]),
    .B1(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o211ai_2 _354_ (
    .A1(b[27]),
    .A2(a[27]),
    .B1(_036_),
    .C1(_158_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21oi_2 _355_ (
    .A1(b[27]),
    .A2(a[27]),
    .B1(_042_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a22oi_2 _356_ (
    .A1(_042_),
    .A2(_153_),
    .B1(_160_),
    .B2(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a221oi_2 _357_ (
    .A1(_042_),
    .A2(_153_),
    .B1(_160_),
    .B2(_161_),
    .C1(_031_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o21ai_2 _358_ (
    .A1(_030_),
    .A2(_162_),
    .B1(_032_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__o221ai_2 _359_ (
    .A1(b[29]),
    .A2(a[29]),
    .B1(_030_),
    .B2(_162_),
    .C1(_032_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a2bb2oi_2 _360_ (
    .A1_N(b[30]),
    .A2_N(a[30]),
    .B1(_028_),
    .B2(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o311ai_2 _361_ (
    .A1(_027_),
    .A2(_030_),
    .A3(_163_),
    .B1(_029_),
    .C1(_026_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__o211ai_2 _362_ (
    .A1(_000_),
    .A2(_001_),
    .B1(_028_),
    .C1(_165_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__o21ai_2 _363_ (
    .A1(b[30]),
    .A2(a[30]),
    .B1(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o221ai_2 _364_ (
    .A1(b[30]),
    .A2(a[30]),
    .B1(_020_),
    .B2(_021_),
    .C1(_168_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__o211ai_2 _365_ (
    .A1(_000_),
    .A2(_001_),
    .B1(_023_),
    .C1(_167_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_2 _366_ (
    .A(_170_),
    .B(_171_),
    .Y(\carry_ripple[7].RA.full_adder[3].FA.out )
  );
  sky130_fd_sc_hd__o221ai_2 _367_ (
    .A1(b[31]),
    .A2(a[31]),
    .B1(b[30]),
    .B2(a[30]),
    .C1(_168_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__o31a_2 _368_ (
    .A1(_021_),
    .A2(_024_),
    .A3(_166_),
    .B1(_172_),
    .X(overflow)
  );
  sky130_fd_sc_hd__nor2_2 _369_ (
    .A(_030_),
    .B(_031_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nand2_2 _370_ (
    .A(_028_),
    .B(_029_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__or4_2 _371_ (
    .A(_024_),
    .B(_025_),
    .C(_030_),
    .D(_031_),
    .X(_175_)
  );
  sky130_fd_sc_hd__or3_2 _372_ (
    .A(_021_),
    .B(_174_),
    .C(_175_),
    .X(_176_)
  );
  sky130_fd_sc_hd__o22ai_2 _373_ (
    .A1(b[31]),
    .A2(a[31]),
    .B1(_176_),
    .B2(_162_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a31oi_2 _374_ (
    .A1(_169_),
    .A2(_176_),
    .A3(_022_),
    .B1(_177_),
    .Y(cout)
  );
  sky130_fd_sc_hd__o2111ai_2 _375_ (
    .A1(_079_),
    .A2(_087_),
    .B1(_080_),
    .C1(_002_),
    .D1(_003_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _376_ (
    .A1_N(_078_),
    .A2_N(_089_),
    .B1(_091_),
    .B2(_178_),
    .X(\carry_ripple[0].RA.full_adder[3].FA.out )
  );
  sky130_fd_sc_hd__o2111a_2 _377_ (
    .A1(b[1]),
    .A2(a[1]),
    .B1(b[2]),
    .C1(a[2]),
    .D1(_085_),
    .X(_179_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _378_ (
    .A1_N(_079_),
    .A2_N(_087_),
    .B1(_089_),
    .B2(_179_),
    .X(\carry_ripple[0].RA.full_adder[2].FA.out )
  );
  sky130_fd_sc_hd__and4_2 _379_ (
    .A(_081_),
    .B(_082_),
    .C(b[1]),
    .D(a[1]),
    .X(_180_)
  );
  sky130_fd_sc_hd__a2111o_2 _380_ (
    .A1(b[0]),
    .A2(a[0]),
    .B1(_083_),
    .C1(a[1]),
    .D1(b[1]),
    .X(_181_)
  );
  sky130_fd_sc_hd__a21o_2 _381_ (
    .A1(_087_),
    .A2(_181_),
    .B1(_180_),
    .X(\carry_ripple[0].RA.full_adder[1].FA.out )
  );
  sky130_fd_sc_hd__and3_2 _382_ (
    .A(cin),
    .B(b[0]),
    .C(a[0]),
    .X(_182_)
  );
  sky130_fd_sc_hd__or2_2 _383_ (
    .A(_182_),
    .B(_084_),
    .X(_183_)
  );
  sky130_fd_sc_hd__o21a_2 _384_ (
    .A1(cin),
    .A2(_081_),
    .B1(_183_),
    .X(\carry_ripple[0].RA.full_adder[0].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _385_ (
    .A(_071_),
    .B(_098_),
    .Y(\carry_ripple[1].RA.full_adder[3].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _386_ (
    .A(_067_),
    .B(_096_),
    .Y(\carry_ripple[1].RA.full_adder[2].FA.out )
  );
  sky130_fd_sc_hd__o221ai_2 _387_ (
    .A1(b[4]),
    .A2(a[4]),
    .B1(_072_),
    .B2(_073_),
    .C1(_093_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__o21ai_2 _388_ (
    .A1(_072_),
    .A2(_095_),
    .B1(_184_),
    .Y(\carry_ripple[1].RA.full_adder[1].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _389_ (
    .A(_070_),
    .B(_091_),
    .Y(\carry_ripple[1].RA.full_adder[0].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _390_ (
    .A(_108_),
    .B(_115_),
    .Y(\carry_ripple[2].RA.full_adder[3].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _391_ (
    .A(_106_),
    .B(_113_),
    .Y(\carry_ripple[2].RA.full_adder[2].FA.out )
  );
  sky130_fd_sc_hd__a21o_2 _392_ (
    .A1(_010_),
    .A2(_011_),
    .B1(_111_),
    .X(_185_)
  );
  sky130_fd_sc_hd__xnor2_2 _393_ (
    .A(_107_),
    .B(_185_),
    .Y(\carry_ripple[2].RA.full_adder[1].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _394_ (
    .A(_102_),
    .B(_103_),
    .Y(\carry_ripple[2].RA.full_adder[0].FA.out )
  );
  sky130_fd_sc_hd__a21oi_2 _395_ (
    .A1(_062_),
    .A2(_125_),
    .B1(_129_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__and3_2 _396_ (
    .A(_062_),
    .B(_125_),
    .C(_129_),
    .X(_187_)
  );
  sky130_fd_sc_hd__nor2_2 _397_ (
    .A(_186_),
    .B(_187_),
    .Y(\carry_ripple[3].RA.full_adder[3].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _398_ (
    .A(_124_),
    .B(_130_),
    .Y(\carry_ripple[3].RA.full_adder[2].FA.out )
  );
  sky130_fd_sc_hd__o21a_2 _399_ (
    .A1(b[12]),
    .A2(a[12]),
    .B1(_120_),
    .X(_188_)
  );
  sky130_fd_sc_hd__xor2_2 _400_ (
    .A(_127_),
    .B(_188_),
    .X(\carry_ripple[3].RA.full_adder[1].FA.out )
  );
  sky130_fd_sc_hd__a221o_2 _401_ (
    .A1(_102_),
    .A2(_110_),
    .B1(_116_),
    .B2(_117_),
    .C1(_128_),
    .X(_189_)
  );
  sky130_fd_sc_hd__o21ai_2 _402_ (
    .A1(_121_),
    .A2(_120_),
    .B1(_189_),
    .Y(\carry_ripple[3].RA.full_adder[0].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _403_ (
    .A(_060_),
    .B(_140_),
    .Y(\carry_ripple[4].RA.full_adder[3].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _404_ (
    .A(_058_),
    .B(_138_),
    .Y(\carry_ripple[4].RA.full_adder[2].FA.out )
  );
  sky130_fd_sc_hd__o21ba_2 _405_ (
    .A1(_054_),
    .A2(_134_),
    .B1_N(_053_),
    .X(_190_)
  );
  sky130_fd_sc_hd__xor2_2 _406_ (
    .A(_059_),
    .B(_190_),
    .X(\carry_ripple[4].RA.full_adder[1].FA.out )
  );
  sky130_fd_sc_hd__xor2_2 _407_ (
    .A(_055_),
    .B(_134_),
    .X(\carry_ripple[4].RA.full_adder[0].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _408_ (
    .A(_050_),
    .B(_149_),
    .Y(\carry_ripple[5].RA.full_adder[3].FA.out )
  );
  sky130_fd_sc_hd__xor2_2 _409_ (
    .A(_048_),
    .B(_147_),
    .X(\carry_ripple[5].RA.full_adder[2].FA.out )
  );
  sky130_fd_sc_hd__o21ba_2 _410_ (
    .A1(_044_),
    .A2(_143_),
    .B1_N(_043_),
    .X(_191_)
  );
  sky130_fd_sc_hd__xor2_2 _411_ (
    .A(_049_),
    .B(_191_),
    .X(\carry_ripple[5].RA.full_adder[1].FA.out )
  );
  sky130_fd_sc_hd__xor2_2 _412_ (
    .A(_045_),
    .B(_143_),
    .X(\carry_ripple[5].RA.full_adder[0].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _413_ (
    .A(_040_),
    .B(_159_),
    .Y(\carry_ripple[6].RA.full_adder[3].FA.out )
  );
  sky130_fd_sc_hd__xnor2_2 _414_ (
    .A(_038_),
    .B(_157_),
    .Y(\carry_ripple[6].RA.full_adder[2].FA.out )
  );
  sky130_fd_sc_hd__or2_2 _415_ (
    .A(_033_),
    .B(_154_),
    .X(_192_)
  );
  sky130_fd_sc_hd__xnor2_2 _416_ (
    .A(_039_),
    .B(_192_),
    .Y(\carry_ripple[6].RA.full_adder[1].FA.out )
  );
  sky130_fd_sc_hd__xor2_2 _417_ (
    .A(_035_),
    .B(_152_),
    .X(\carry_ripple[6].RA.full_adder[0].FA.out )
  );
  sky130_fd_sc_hd__a2bb2oi_2 _418_ (
    .A1_N(_024_),
    .A2_N(_025_),
    .B1(_028_),
    .B2(_165_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__o21bai_2 _419_ (
    .A1(_025_),
    .A2(_168_),
    .B1_N(_193_),
    .Y(\carry_ripple[7].RA.full_adder[2].FA.out )
  );
  sky130_fd_sc_hd__xor2_2 _420_ (
    .A(_164_),
    .B(_174_),
    .X(\carry_ripple[7].RA.full_adder[1].FA.out )
  );
  sky130_fd_sc_hd__xor2_2 _421_ (
    .A(_162_),
    .B(_173_),
    .X(\carry_ripple[7].RA.full_adder[0].FA.out )
  );
  sky130_fd_sc_hd__buf_2 _422_ (
    .A(\carry_ripple[0].RA.full_adder[0].FA.out ),
    .X(sum[0])
  );
  sky130_fd_sc_hd__buf_2 _423_ (
    .A(\carry_ripple[0].RA.full_adder[1].FA.out ),
    .X(sum[1])
  );
  sky130_fd_sc_hd__buf_2 _424_ (
    .A(\carry_ripple[0].RA.full_adder[2].FA.out ),
    .X(sum[2])
  );
  sky130_fd_sc_hd__buf_2 _425_ (
    .A(\carry_ripple[0].RA.full_adder[3].FA.out ),
    .X(sum[3])
  );
  sky130_fd_sc_hd__buf_2 _426_ (
    .A(\carry_ripple[1].RA.full_adder[0].FA.out ),
    .X(sum[4])
  );
  sky130_fd_sc_hd__buf_2 _427_ (
    .A(\carry_ripple[1].RA.full_adder[1].FA.out ),
    .X(sum[5])
  );
  sky130_fd_sc_hd__buf_2 _428_ (
    .A(\carry_ripple[1].RA.full_adder[2].FA.out ),
    .X(sum[6])
  );
  sky130_fd_sc_hd__buf_2 _429_ (
    .A(\carry_ripple[1].RA.full_adder[3].FA.out ),
    .X(sum[7])
  );
  sky130_fd_sc_hd__buf_2 _430_ (
    .A(\carry_ripple[2].RA.full_adder[0].FA.out ),
    .X(sum[8])
  );
  sky130_fd_sc_hd__buf_2 _431_ (
    .A(\carry_ripple[2].RA.full_adder[1].FA.out ),
    .X(sum[9])
  );
  sky130_fd_sc_hd__buf_2 _432_ (
    .A(\carry_ripple[2].RA.full_adder[2].FA.out ),
    .X(sum[10])
  );
  sky130_fd_sc_hd__buf_2 _433_ (
    .A(\carry_ripple[2].RA.full_adder[3].FA.out ),
    .X(sum[11])
  );
  sky130_fd_sc_hd__buf_2 _434_ (
    .A(\carry_ripple[3].RA.full_adder[0].FA.out ),
    .X(sum[12])
  );
  sky130_fd_sc_hd__buf_2 _435_ (
    .A(\carry_ripple[3].RA.full_adder[1].FA.out ),
    .X(sum[13])
  );
  sky130_fd_sc_hd__buf_2 _436_ (
    .A(\carry_ripple[3].RA.full_adder[2].FA.out ),
    .X(sum[14])
  );
  sky130_fd_sc_hd__buf_2 _437_ (
    .A(\carry_ripple[3].RA.full_adder[3].FA.out ),
    .X(sum[15])
  );
  sky130_fd_sc_hd__buf_2 _438_ (
    .A(\carry_ripple[4].RA.full_adder[0].FA.out ),
    .X(sum[16])
  );
  sky130_fd_sc_hd__buf_2 _439_ (
    .A(\carry_ripple[4].RA.full_adder[1].FA.out ),
    .X(sum[17])
  );
  sky130_fd_sc_hd__buf_2 _440_ (
    .A(\carry_ripple[4].RA.full_adder[2].FA.out ),
    .X(sum[18])
  );
  sky130_fd_sc_hd__buf_2 _441_ (
    .A(\carry_ripple[4].RA.full_adder[3].FA.out ),
    .X(sum[19])
  );
  sky130_fd_sc_hd__buf_2 _442_ (
    .A(\carry_ripple[5].RA.full_adder[0].FA.out ),
    .X(sum[20])
  );
  sky130_fd_sc_hd__buf_2 _443_ (
    .A(\carry_ripple[5].RA.full_adder[1].FA.out ),
    .X(sum[21])
  );
  sky130_fd_sc_hd__buf_2 _444_ (
    .A(\carry_ripple[5].RA.full_adder[2].FA.out ),
    .X(sum[22])
  );
  sky130_fd_sc_hd__buf_2 _445_ (
    .A(\carry_ripple[5].RA.full_adder[3].FA.out ),
    .X(sum[23])
  );
  sky130_fd_sc_hd__buf_2 _446_ (
    .A(\carry_ripple[6].RA.full_adder[0].FA.out ),
    .X(sum[24])
  );
  sky130_fd_sc_hd__buf_2 _447_ (
    .A(\carry_ripple[6].RA.full_adder[1].FA.out ),
    .X(sum[25])
  );
  sky130_fd_sc_hd__buf_2 _448_ (
    .A(\carry_ripple[6].RA.full_adder[2].FA.out ),
    .X(sum[26])
  );
  sky130_fd_sc_hd__buf_2 _449_ (
    .A(\carry_ripple[6].RA.full_adder[3].FA.out ),
    .X(sum[27])
  );
  sky130_fd_sc_hd__buf_2 _450_ (
    .A(\carry_ripple[7].RA.full_adder[0].FA.out ),
    .X(sum[28])
  );
  sky130_fd_sc_hd__buf_2 _451_ (
    .A(\carry_ripple[7].RA.full_adder[1].FA.out ),
    .X(sum[29])
  );
  sky130_fd_sc_hd__buf_2 _452_ (
    .A(\carry_ripple[7].RA.full_adder[2].FA.out ),
    .X(sum[30])
  );
  sky130_fd_sc_hd__buf_2 _453_ (
    .A(\carry_ripple[7].RA.full_adder[3].FA.out ),
    .X(sum[31])
  );
endmodule
